<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [157]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    if len(A)==len(B):
        #C= [[0]*len(B[0])]*len(A)
        C = [[0 for i in range(len(B[0]))] for j in range(len(A))]
        for i in range(0,len(A)):
            for j in range(0,len(B[0])):
                for k in range(0,len(A)):
                    C[i][j]+=A[i][k]*B[k][j]
        return C
    else:
        print('Not Possible')
A   = [[1,2],[3,4]]
B   = [[1,4],[5,6]]   
matrix_mul(A,B)


[[11, 16], [23, 36]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [158]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    s=sum(A)
    l1=[]
    for i in A:
        #print(i/s)
        l1.append(i/s)
    #print('************************')
    l2=[]
    s1=0
    for i in l1:
        s1+=i
        #print(s1)
        l2.append(s1)
    #print('************************')
    r=random.uniform(0,1)
    #print(r)
    for i in l2:
        if r<=i:
            return A[l2.index(i)]
        
def sampling_based_on_magnitued(A):
    k=[]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        k.append(number)
    A.sort(reverse=True)
    for i in A:
        print(i,k.count(i))
A = [0,5,27,6,13,28,100,45,10,79]
sampling_based_on_magnitued(A)

100 32
79 21
45 15
28 9
27 11
13 3
10 3
6 1
5 4
0 0


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [159]:

import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    return ''.join('#' for i in ''.join(filter(str.isdigit,String))) # modified string which is after replacing the # with digits
String = '#2a$#b%c%561#'
replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [160]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(s, m):
    k=m.copy()
    k.sort(reverse=True)
    print('Top 5 students')
    for i in range(0,5):
        print(str(s[m.index(k[i])])+':'+str(m[m.index(k[i])]))
    print('\n')
    print('Least 5 students')
    for i in range(len(k)-1,(len(k)-1)-5,-1):
        print(str(s[m.index(k[i])])+':'+str(m[m.index(k[i])]))
    print('\n')
    print('Students who got marks between >25th percentile <75th percentile')
    maximum = max(k)   
    k.sort()
    for i in k:
        if i/maximum > 0.25 and i/maximum < 0.75:
            print(str(s[m.index(i)])+':'+str(m[m.index(i)]))
    


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks=[45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students, marks)



Top 5 students
student8:98
student10:80
student2:78
student5:48
student7:47


Least 5 students
student3:12
student4:14
student9:35
student6:43
student1:45


Students who got marks between >25th percentile <75th percentile
student9:35
student6:43
student1:45
student7:47
student5:48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [161]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(s, p):
    l=[]
    closest_points_to_p=[]
    for i in range(0,len(s)):
        val=math.acos((s[i][0]*p[0]+s[i][1]*p[1])/(((s[i][0]**2 + s[i][1]**2)**0.5)*(p[0]**2 + p[1]**2)**0.5))
        l.append(val)
        val=0
    k=l.copy()
    k.sort()
    for i in range(0,5):
        closest_points_to_p.append(s[l.index(k[i])])
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points)

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [162]:
import re
def ret_coeff(Lines):
    for i in range(0,len(Lines)):
        result = [d for d in re.findall(r'[\d\.\-\+]+',Lines[i])]
        #print(result)
        Lines[i] = (result[0],result[1],result[2])
        result*=0 
    return Lines


Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
line = ret_coeff(Lines)
r=[]
b=[]
c=1
red=[(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue=[(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
for k in range(0,len(line)):
    for i in range(0,len(red)):
            d = (float(line[k][0])*red[i][0] + float(line[k][1])*red[i][1] + float(line[k][2])) / (((float(line[k][0])**2)+(float(line[k][1])**2))**0.5)
            r.append(d)
            d=0
    #print(r)
    for i in range(0,len(blue)):
            d = (float(line[k][0])*blue[i][0] + float(line[k][1])*blue[i][1] + float(line[k][2])) / (((float(line[k][0])**2)+(float(line[k][1])**2))**0.5)
            b.append(d)
            d=0
    #print(b)
    for i in range(0,len(b)):
            if (r[i]>0 and b[i]<0) or (r[i]<0 and b[i]>0):
                c=1
            else:
                c=0
                break
    if c==1:
        print('YES')
    else:
        print('NO')
    r*=0
    b*=0


    

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [163]:
#this one was difficult to solve for me. got help from stack overflow.
def curve_smoothing(string):
    x = list(string.split(","))
    print(x)
    y=[]
    for i in x:
        if i!='_':
            y.append(x.index(i))
    first=0
    last=-1
    #this if excludes if value present in index 0
    if y[first] != 0:
        y.insert(0,-1)
    #this of excludes if value is present at the end
    if y[last] != len(x)-1:
        y.insert(len(x),-1)
    
    for (a, b) in zip(y[0:], y[1:]): 
        if a == -1:
            value = float(x[b])/(b+1)
            for i in range(a+1,b+1):
                x[i] = value
        elif b == -1:
            value = float(x[a])/(len(x)-a)
            for i in range(a, len(x)):
                x[i] = value
        else:
            value = (float(x[a])+float(x[b]))/(b-a+1)
            for i in range(a,b+1):
                x[i] = value
    return x
    
S=  "_,_,_,24"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

['_', '_', '_', '24']
[6.0, 6.0, 6.0, 6.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [164]:
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

def count(char1,char2,A):
    counts=0
    for i in range(0,len(A)):
        if char2==A[i][1]:
            counts+=1
            
    return counts

def compute_conditional_probabilites(char1,char2,A):
    counts = count(char1,char2,A)
    return str((A.count([char1,char2])))+'/'+str(counts)

print('P(F=F1|S==S1) :',compute_conditional_probabilites('F1','S1',A),
      'P(F=F1|S==S2) :',compute_conditional_probabilites('F1','S2',A),
      'P(F=F1|S==S3) :',compute_conditional_probabilites('F1','S3',A))
print()
print()
print('P(F=F2|S==S1) :',compute_conditional_probabilites('F2','S1',A),
      'P(F=F2|S==S2) :',compute_conditional_probabilites('F2','S2',A),
      'P(F=F2|S==S3) :',compute_conditional_probabilites('F2','S3',A))
print()
print()
print('P(F=F3|S==S1) :',compute_conditional_probabilites('F3','S1',A),
      'P(F=F3|S==S2) :',compute_conditional_probabilites('F3','S2',A),
      'P(F=F3|S==S3) :',compute_conditional_probabilites('F3','S3',A))
print()
print()
print('P(F=F4|S==S1) :',compute_conditional_probabilites('F4','S1',A),
      'P(F=F4|S==S2) :',compute_conditional_probabilites('F4','S2',A),
      'P(F=F4|S==S3) :',compute_conditional_probabilites('F4','S3',A))
print()
print()
print('P(F=F5|S==S1) :',compute_conditional_probabilites('F5','S1',A),
      'P(F=F5|S==S2) :',compute_conditional_probabilites('F5','S2',A),
      'P(F=F5|S==S3) :',compute_conditional_probabilites('F5','S3',A))
print()
print()
            

P(F=F1|S==S1) : 1/4 P(F=F1|S==S2) : 1/3 P(F=F1|S==S3) : 0/3


P(F=F2|S==S1) : 1/4 P(F=F2|S==S2) : 1/3 P(F=F2|S==S3) : 1/3


P(F=F3|S==S1) : 0/4 P(F=F3|S==S2) : 1/3 P(F=F3|S==S3) : 1/3


P(F=F4|S==S1) : 1/4 P(F=F4|S==S2) : 0/3 P(F=F4|S==S3) : 1/3


P(F=F5|S==S1) : 1/4 P(F=F5|S==S2) : 0/3 P(F=F5|S==S3) : 0/3




<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [165]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    s1=S1.split()
    s2=S2.split()
    a=0
    b,c=[],[]
    for i in s1:
        if i in s2:
            a+=1
        else:
            b.append(i)
    for i in s2:
        if i not in s1:
            c.append(i)
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a,b,c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [166]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    n=len(A)
    loss=0
    for i in range(0,len(A)):
        loss+=(  (A[i][0]*(math.log10(A[i][1]))) + (1-A[i][0])*(math.log10((1-A[i][1]))) )
    loss*=(-1/n)
               
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
