# <font color='red'><b>Bootstrap assignment</b> </font>

<b>There will be some functions that start with the word "grader" ex: grader_sampples(), grader_30().. etc, you should not change those function definition.

Every Grader function has to return True.</b>

<font color='blue'> <b>Importing packages</b> </font>

In [1]:
import numpy as np # importing numpy for numerical computation
from sklearn.datasets import load_boston # here we are using sklearn's boston dataset
from sklearn.metrics import mean_squared_error # importing mean_squared_error metric
from statistics import median
from sklearn.tree import DecisionTreeRegressor
import random
from prettytable import PrettyTable


In [2]:
boston = load_boston()
x=boston.data #independent variables
y=boston.target #target variable

In [3]:
x.shape

(506, 13)

In [4]:
x[:5]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01,
        6.5750e+00, 6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02,
        1.5300e+01, 3.9690e+02, 4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        6.4210e+00, 7.8900e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9690e+02, 9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, 0.0000e+00, 4.6900e-01,
        7.1850e+00, 6.1100e+01, 4.9671e+00, 2.0000e+00, 2.4200e+02,
        1.7800e+01, 3.9283e+02, 4.0300e+00],
       [3.2370e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        6.9980e+00, 4.5800e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9463e+02, 2.9400e+00],
       [6.9050e-02, 0.0000e+00, 2.1800e+00, 0.0000e+00, 4.5800e-01,
        7.1470e+00, 5.4200e+01, 6.0622e+00, 3.0000e+00, 2.2200e+02,
        1.8700e+01, 3.9690e+02, 5.3300e+00]])

## <font color='red'><b>Task 1</b></font>

<font color='red'> <b>Step - 1</b></font>

*  <font color='blue'><b>Creating samples</b></font><br>
    <b> Randomly create 30 samples from the whole boston data points</b>
    *  Creating each sample: Consider any random 303(60% of 506) data points from whole data set and then replicate any 203 points from the sampled points
    
     For better understanding of this procedure lets check this examples, assume we have 10 data points [1,2,3,4,5,6,7,8,9,10], first we take 6 data points randomly , consider we have selected [4, 5, 7, 8, 9, 3] now we will replicate 4 points from [4, 5, 7, 8, 9, 3], consder they are [5, 8, 3,7] so our final sample will be [4, 5, 7, 8, 9, 3, 5, 8, 3,7]
* <font color='blue'><b> Create 30 samples </b></font>
    *  Note that as a part of the Bagging when you are taking the random samples <b>make sure each of the sample will have different set of columns</b><br>
Ex: Assume we have 10 columns[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10] for the first sample we will select [3, 4, 5, 9, 1, 2] and for the second sample  [7, 9, 1, 4, 5, 6, 2] and so on...
Make sure each sample will have atleast 3 feautres/columns/attributes

<font color='red'><b>Step - 2 </b></font>

<font color='blue'><b>Building High Variance Models on each of the sample and finding train MSE value</b></font>

*  Build a regression trees on each of 30 samples.
*  Computed the predicted values of each data point(506 data points) in your corpus.
*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{30}\sum_{k=1}^{30}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$
*  Now calculate the $MSE =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$

<font color='red'> <b>Step - 3 </b></font>

*  <font color='blue'><b>Calculating the OOB score </b></font>

*  Predicted house price of $i^{th}$ data point $y^{i}_{pred} =  \frac{1}{k}\sum_{\text{k= model which was buit on samples not included } x^{i}}(\text{predicted value of } x^{i} \text{ with } k^{th} \text{ model})$.
*  Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

# <font color='red'><b>Task 2</b></font>

*  <font color='blue'><b>Computing CI of OOB Score and Train MSE</b></font>
  *   Repeat Task 1 for 35 times, and for each iteration store the Train MSE and OOB score </li>
<li> After this we will have 35 Train MSE values and 35 OOB scores </li>
<li> using these 35 values (assume like a sample) find the confidence intravels of MSE and OOB Score </li>
<li> you need to report CI of MSE and CI of OOB Score </li>
<li> Note: Refer the Central_Limit_theorem.ipynb to check how to find the confidence intravel</li>
</ol>

# <font color='red'><b>Task 3</b></font>

*  <font color='blue'><b>Given a single query point predict the price of house.</b></font>

Consider xq= [0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60] 
Predict the house price for this point as mentioned in the step 2 of Task 1.

<br><br><br>

# <font color='blue'> <b>Task - 1</b></font>

<font color='blue'><b>Step - 1</b></font>

*  <font color='blue'> <b>Creating samples</b></font>

<font color='Orange'><b>Algorithm</b></font>

![alt text](https://i.imgur.com/BTVYXQ1.jpg/)

*  <font color='blue'><b> Write code for generating samples</b></font>

In [5]:
def generating_samples(input_data, target_data):

    '''In this function, we will write code for generating 30 samples '''

    selecting_rows=np.random.choice(len(input_data),303,replace=False)
    replacing_rows=np.random.choice(selecting_rows,203,replace=False)
  
    #Creating column samples
    select_col_no = random.randint(3, 13)
    selecting_columns = np.array(random.sample(range(0, 13), select_col_no ))
    
    
    sample_data = input_data[selecting_rows[:, None], selecting_columns]
    target_of_sample_data = target_data[selecting_rows]

    #Replicating data

    replicated_sample_data=input_data[replacing_rows[:,None],selecting_columns]
    target_of_replicated_sample_data = target_data[replacing_rows]

    #Concatenating Data

    final_sample_data = np.vstack((sample_data, replicated_sample_data))
    final_target_data = np.vstack((target_of_sample_data.reshape(-1, 1), target_of_replicated_sample_data.reshape(-1, 1)))

    return final_sample_data,final_target_data,selecting_rows,selecting_columns


<font color='cyan'> <b> Grader function - 1 </b> </fongt>

In [6]:
def grader_samples(a,b,c,d):
    length = (len(a)==506  and len(b)==506)
    sampled = (len(a)-len(set([str(i) for i in a]))==203)
    rows_length = (len(c)==303)
    column_length= (len(d)>=3)
    assert(length and sampled and rows_length and column_length)
    return True
a,b,c,d = generating_samples(x, y)
grader_samples(a,b,c,d)

True

*  <font color='blue'> <b>Create 30 samples </b>

![alt text](https://i.imgur.com/p8eZaWL.jpg)

In [7]:
def gen_30_samples(x,y):
# Use generating_samples function to create 30 samples 
# store these created samples in a list
    list_input_data =[]
    list_output_data =[]
    list_selected_row= []
    list_selected_columns=[]

    for i in range(0,30):
        a,b,c,d = generating_samples(x,y)
        list_input_data.append(a)
        list_output_data.append(b)
        list_selected_row.append(c)
        list_selected_columns.append(d)

    return list_input_data,list_output_data,list_selected_row,list_selected_columns



In [8]:
list_input_data,list_output_data,list_selected_row,list_selected_columns=gen_30_samples(x,y)

<font color='cyan'> <b>Grader function - 2 </b></font>

In [9]:
def grader_30(a):
    assert(len(a)==30 and len(a[0])==506)
    return True
grader_30(list_input_data)

True

<br>

<font color='red'><b>Step - 2 </b></font>

<font color='orange'><b>Flowchart for building tree</b></font>

![alt text](https://i.imgur.com/pcXfSmp.png)

*  <font color='blue'><b> Write code for building regression trees</b></font>

In [140]:
def build_reg_trees(list_input_data,list_output_data):

    dt_reg_model = []
    y_predict = []
    for i in range(30):
        model = DecisionTreeRegressor(max_depth=None)
        model.fit(list_input_data[i],list_output_data[i])
        dt_reg_model.append(model)

    for i in range(30):
        predict_model = dt_reg_model[i].predict(x[:,list_selected_columns[i]])
        y_predict.append(predict_model)

    y_predict = np.array(y_predict)
    y_predict = y_predict.transpose()

    return y_predict,dt_reg_model



In [115]:
y_predict,dt_reg_model = build_reg_trees(list_input_data,list_output_data)
print(y_predict)

[[24.  16.5 31.2 ... 22.  24.  27.1]
 [22.  19.9 21.6 ... 25.3 21.6 21.6]
 [34.7 34.7 34.7 ... 34.7 34.7 28.7]
 ...
 [23.9 23.9 23.9 ... 23.6 23.9 29.8]
 [22.  25.  22.  ... 22.  22.  22. ]
 [11.9 20.6 11.9 ... 11.9 11.9 11.9]]


<font color='orange'><b>Flowchart for calculating MSE </b></font>

![alt text](https://i.imgur.com/sPEE618.png)

After getting predicted_y for each data point, we can use sklearns mean_squared_error to calculate the MSE between predicted_y and actual_y.

*  <font color='blue'><b> Write code for calculating MSE</b></font>

In [138]:
def calculate_mean_sq_error(y_predict):
    predicted_median = np.median(y_predict,axis=1)

    mean_sq_error =  mean_squared_error(y,predicted_median)
    
    return mean_sq_error


In [113]:
mean_sq_error=calculate_mean_sq_error(y_predict)
print('The Mean Square Error obtained is :  {}'.format(mean_sq_error))

The Mean Square Error obtained is :  0.057179951690821296


<font color='blue'><b>Step - 3 </b></font>

<font color='orange'><b>Flowchart for calculating OOB score</b></font>

![alt text](https://i.imgur.com/95S5Mtm.png)

Now calculate the $OOB Score =  \frac{1}{506}\sum_{i=1}^{506}(y^{i} - y^{i}_{pred})^{2}$.

*  <font color='blue'><b> Write code for calculating OOB score </b></font>

In [127]:
def calculate_oob_score(list_selected_row,dt_reg_model,x):
    y_predict_oob_list = []

    for i in range(506):
        pt = []

        for j in range(30):
            if(i not in list_selected_row[j]):
               pt.append(j)
        y_preds_oob = []

        for model in pt:
           model_oob = dt_reg_model[model]
           row = x[i]
           x_oob = [row[column] for column in list_selected_columns[model]]
           x_oob = np.array(x_oob).reshape(1,-1)
           y_pred_oob = model_oob.predict(x_oob)
           y_preds_oob.append(y_pred_oob)
        y_preds_oob_median = np.median(np.array(y_preds_oob))
        y_predict_oob_list.append(y_preds_oob_median)


    oob_score = 0
    for i in range(506):
        oob_score += ((y[i]-y_predict_oob_list[i]) ** 2)
    oob_score = oob_score/506

    return oob_score

In [128]:
print('The Obtained OOB Score is {}'.format(calculate_oob_score(list_selected_row,dt_reg_model,x)))

The Obtained OOB Score is 15.384079518006148


# <font color='blue'><b>Task 2</b></font>

In [145]:
#Checking if functions are working
list_input_data,list_output_data,list_selected_row,list_selected_columns=gen_30_samples(x,y)
y_predict,dt_reg_model = build_reg_trees(list_input_data,list_output_data)
mean_sq_error=calculate_mean_sq_error(y_predict)
oob_score=calculate_oob_score(list_selected_row,dt_reg_model,x)

print(mean_sq_error)
print(oob_score)






0.13048913043478266
13.182218379446626


In [146]:
x=boston.data #independent variables
y=boston.target #target variable

mean_sq_error_list = []
oob_scores_list = []
for i in range(35):
    list_input_data,list_output_data,list_selected_row,list_selected_columns=gen_30_samples(x,y)
    y_predict,dt_reg_model = build_reg_trees(list_input_data,list_output_data)
    mean_sq_error=calculate_mean_sq_error(y_predict)
    oob_score=calculate_oob_score(list_selected_row,dt_reg_model,x)   
    mean_sq_error_list.append(mean_sq_error)
    oob_scores_list.append(oob_score)

mean_sq_error_array= np.array(mean_sq_error_list)
oob_scores_array = np.array(oob_scores_list)

In [147]:
print(mean_sq_error_array)
print(oob_scores_array)

[0.03016304 0.11605731 0.13417984 0.25357354 0.04913538 0.31685268
 0.07759103 0.03198177 0.03908597 0.17856225 0.05212451 0.081833
 0.06056478 0.10107213 0.02759387 0.05392342 0.09831923 0.08361606
 0.27084015 0.13227767 0.08610521 0.30781169 0.07070707 0.06333368
 0.06105676 0.13159091 0.09162549 0.10996294 0.02355731 0.19146166
 0.02841403 0.08686759 0.01161561 0.10492136 0.1088834 ]
[14.65921443 13.54837945 11.34489954 13.0267005  12.81639044 14.92688241
 13.83255349 12.65890593 16.25762964 15.8757703  12.42894199 14.64453063
 14.68291068 12.29350904 13.26867589 14.28023525 16.70725654 14.3955008
 15.05399912 13.74592507 10.49402085 12.94474933 14.77789032  9.9559041
 13.68037875 14.21315219 14.84876976 15.8888573  14.44325716 13.30577295
 13.60087813 13.12079821 15.86025911 12.78819229 12.65929977]


Calculating Confidence Interval

In [158]:
def cal_CI(input_data):
    '''
      Function to calculate Confidence interval
    '''
    x = PrettyTable()
    x = PrettyTable(["SL No:", "Sample Size", "Sample mean", "Sample std", "Population mean","Left C.I","Right C.I","Match"])
    Population_mean = input_data.mean()
    for i in range(10):
        sample = input_data[np.random.choice(input_data.shape[0],size = 20)]
        sample_size = len(sample)
        sample_mean = sample.mean()
        sample_std =  sample.std()

        left_ci_limit  = np.round(sample_mean - 2*(sample_std/np.sqrt(sample_size)), 3)
        right_ci_limit = np.round(sample_mean + 2*(sample_std/np.sqrt(sample_size)), 3)

        row = []
        row.append(i+1)
        row.append(sample_size)
        row.append(sample_mean)
        row.append(sample_std)
        row.append(Population_mean)
        row.append(left_ci_limit)
        row.append(right_ci_limit)
        row.append((Population_mean <= right_limit) and (Population_mean >= left_limit))
        x.add_row(row)
    
    print(x)

In [159]:
cal_CI(mean_sq_error_array)

+--------+-------------+---------------------+----------------------+---------------------+----------+-----------+-------+
| SL No: | Sample Size |     Sample mean     |      Sample std      |   Population mean   | Left C.I | Right C.I | Match |
+--------+-------------+---------------------+----------------------+---------------------+----------+-----------+-------+
|   1    |      20     | 0.11092458788762301 | 0.07529265870235767  | 0.10477892480961046 |  0.077   |   0.145   |  True |
|   2    |      20     | 0.10283323802735231 | 0.07279052237542541  | 0.10477892480961046 |   0.07   |   0.135   |  True |
|   3    |      20     | 0.10950238072338817 | 0.07918409854466464  | 0.10477892480961046 |  0.074   |   0.145   |  True |
|   4    |      20     | 0.11666680779862607 | 0.08532486656616632  | 0.10477892480961046 |  0.079   |   0.155   |  True |
|   5    |      20     | 0.10039377799167588 | 0.09087381465918265  | 0.10477892480961046 |   0.06   |   0.141   |  True |
|   6    |      

In [160]:
cal_CI(oob_scores_array)

+--------+-------------+--------------------+--------------------+--------------------+----------+-----------+-------+
| SL No: | Sample Size |    Sample mean     |     Sample std     |  Population mean   | Left C.I | Right C.I | Match |
+--------+-------------+--------------------+--------------------+--------------------+----------+-----------+-------+
|   1    |      20     | 13.320953474134138 | 1.5153806470597793 | 13.800885467578995 |  12.643  |   13.999  | False |
|   2    |      20     | 14.103700614895441 | 1.0761396363299958 | 13.800885467578995 |  13.622  |   14.585  | False |
|   3    |      20     | 14.090506777732054 | 1.3772609335373673 | 13.800885467578995 |  13.475  |   14.706  | False |
|   4    |      20     | 14.349772099047161 | 1.1499073643418107 | 13.800885467578995 |  13.836  |   14.864  | False |
|   5    |      20     |  14.1286802682794  | 1.3128102814664306 | 13.800885467578995 |  13.542  |   14.716  | False |
|   6    |      20     | 13.404804319187855 | 1.

# <font color='blue'><b>Task 3</b></font>

<font color='orange'><b>Flowchart for Task 3</b></font>

<b>Hint: </b> We created 30 models by using 30 samples in TASK-1. Here, we need send query point "xq"  to 30 models and perform the regression on the output generated by 30 models.

![alt text](https://i.imgur.com/Y5cNhQk.png)

*  <font color='blue'><b> Write code for TASK 3 </b></font>

In [164]:
x=boston.data #independent variables
y=boston.target #target variable

list_input_data,list_output_data,list_selected_row,list_selected_columns=gen_30_samples(x,y)
y_predict,dt_reg_model = build_reg_trees(list_input_data,list_output_data)

In [165]:
xq= np.array([0.18,20.0,5.00,0.0,0.421,5.60,72.2,7.95,7.0,30.0,19.1,372.13,18.60])

predict_value = 0

for i in range(30):
   predict_value+=dt_reg_model[i].predict(np.array([xq[column] for column in list_selected_columns[i]]).reshape(1,-1))

print('The Predicted House Price for the given features is {}'.format(predict_value/30))


The Predicted House Price for the given features is [20.04366667]


<br><br><br>

<font color='red'><b>Write observations for task 1, task 2, task 3 indetail</b></font>

1. The Mean Square Error obtained in Task 1 is considerably high compared to MSE obtained from Task2, implies there exist high variance among the features
2. From the CI obtained, we could see that the mean of OOB score and MSE lie within the CI implies that 95% times the mean calculated from the samples lie in CI
3. Query point was send and the house price was predicted